### ISSUE TITLE
友联添加申请（源站小满の窝）更新

### ISSUE THREAD

**Issue by xiaoman1221** [MagmaBlock/MagmaInk#2]
### 确认

- [X] 已了解 https://magma.ink/links/ 中添加站点的需求

### 站点名称

满久琦的个人网站

### 站点简介

天上如是，地下亦然

### 站点地址

https://www.manjiuqi.com

### 站点头像

https://static.yhdzz.cn/logos/512x512.png

**Comment by MagmaBlock** [comment]
啊是实名上网的大佬... 已添加

**Comment by xiaoman1221** [comment]
哈哈哈
