### ISSUE TITLE
友联添加申请

### ISSUE THREAD

**Issue by Petermusic267** [MagmaBlock/MagmaInk#3]
### 确认

- [X] 已了解 https://magma.ink/links/ 中添加站点的需求

### 站点名称

Peter

### 站点简介

无限进步

### 站点地址

https://peter267.zeabur.app

### 站点头像

https://wmimg.com/i/1169/2024/09/66e8b5d8e0843.jpg

**Comment by MagmaBlock** [comment]
ok，已经添加
